apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod1
  name: ashupod1
spec:
  serviceAccountName: adobe
  imagePullSecrets:
  - name: ashu-azure-secret
  containers:
  - command:
    - sleep
    - "1000"
    image: adobe.azurecr.io/adobe:alpine
    name: ashupod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
