apiVersion: v1
kind: Pod
metadata:
  name: pvc-consumer-pod
spec:
  restartPolicy: Always
  containers:
  - name: pvc-consumer
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command:
    - /bin/sh
    - -c
    - sleep infinity
    volumeMounts:
    - name: backup-storage
      mountPath: /backup
  volumes:
  - name: backup-storage
    persistentVolumeClaim:
      claimName: backup-pvc
